name: VoidWorldGenerator
version: '${version}'
main: dev.haedhutner.voidworldgenerator.VoidWorldGenerator
api-version: '1.20'
load: STARTUP
authors: [HaedHutner]
description: A Void World Generator
website: https://haedhutner.dev
